# -*- coding: utf-8 -*-
"""50_Startsups.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12y1-ToPtuGCvHczr47ftApkUzbVX2GWZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
df=pd.read_csv('50_Startups.csv')
print("\n\n------------------1---------------\n\n")
print(df.describe())
print("\n\n------------------2---------------\n\n")
print(df.info())
le=LabelEncoder()
df['State']=le.fit_transform(df['State'])
plt.scatter(df['R&D Spend'],df['Profit'])
plt.xlabel('R&D Spend')
plt.ylabel('Profit')
plt.show()
print("\n\n------------------3---------------\n\n")
plt.scatter(df['Administration'],df['Profit'])
plt.xlabel("Administration")
plt.ylabel("Profit")
plt.show()
print("\n\n------------------4---------------\n\n")
plt.scatter(df['State'],df['Profit'])
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
df[['R&D Spend','Administration','Marketing Spend','Profit']]=sc.fit_transform(df[['R&D Spend','Administration','Marketing Spend','Profit']])
kmeans=KMeans()
df['Group']=kmeans.fit_predict(df[['R&D Spend','Administration','Marketing Spend','Profit']])
print(df)
print("\n\n------------------5---------------\n\n")
plt.scatter(df['R&D Spend'],df['Group'])
plt.show()
print("\n\n------------------6---------------\n\n")
plt.scatter(df['Administration'],df['Group'])
plt.show()
print("\n\n------------------7---------------\n\n")
plt.scatter(df['Marketing Spend'],df['Group'])
plt.show()
print("\n\n------------------8---------------\n\n")
plt.scatter(df['Profit'],df['Group'])
plt.show()
print("\n\n------------------9---------------\n\n")