# -*- coding: utf-8 -*-
"""Car.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FUTieVt4urb9TZNFHp185-IAdrwLABdO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
df=pd.read_csv('car_data.csv')
print("\n\n-------------------1---------------\n\n")
print(df.describe())
print("\n\n-------------------2---------------\n\n")
print(df.groupby('Brand')['Engine_HP'].mean())
print("\n\n-------------------3---------------\n\n")
print(df.groupby('Brand')['Car_Price'].mean())
a=df['Brand'].value_counts()
b=df['Fuel_Type'].value_counts()
print("\n\n-------------------4---------------\n\n")
print(df.info())
df.duplicated().sum()
print("\n\n-------------------5---------------\n\n")
print(df.shape)
plt.pie(a,labels=a.index,autopct='%1.1f%%')
plt.show()
plt.pie(b,labels=b.index,autopct='%1.1f%%')
plt.show()
plt.xlabel('Brand')
plt.boxplot([df.Engine_HP])
plt.show()
plt.xlabel('Fuel_Type')
plt.boxplot([df.Car_Price])
plt.show()
print("\n\n-------------------6---------------\n\n")
plt.scatter(df.Engine_HP,df.Car_Price,color='g')
plt.show()
print("\n\n-------------------7---------------\n\n")
plt.scatter(df.Engine_HP,df.Year)
plt.show()
print("\n\n-------------------8---------------\n\n")
plt.plot(df.Engine_HP,linestyle='--',color='pink')
plt.show()
print("\n\n-------------------9---------------\n\n")
plt.plot(df.Year,linestyle='--',color='b')
plt.show()
print("\n\n-------------------10---------------\n\n")
from sklearn.preprocessing import MinMaxScaler,StandardScaler
scaler1=MinMaxScaler()
scaler2=StandardScaler()
df['Engine_HP']=scaler1.fit_transform(df[['Engine_HP']])
print("\n\n-------------------11---------------\n\n")
print(df)
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
ohe=OneHotEncoder()
# df['Brand']=ohe.fit_transform(df[['Brand']]).toarray()
# df['Fuel_Type']=ohe.fit_transform(df[['Fuel_Type']]).toarray()
le=LabelEncoder()
df['Brand']=le.fit_transform(df['Brand'])
df['Fuel_Type']=le.fit_transform(df['Fuel_Type'])
print("\n\n-------------------12---------------\n\n")
print(df)
from sklearn.model_selection import train_test_split
X=df.drop(columns='Car_Price')
y=df['Car_Price']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("\n\n-------------------13---------------\n\n")
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print(y_test)
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))