# -*- coding: utf-8 -*-
"""DATA VISUALISATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-xXN4iTZph4XN25pqjvtQi-hGgWHqgw

#MATPLOTLIB CUSTOM DATASETS
"""

import matplotlib.pyplot as plt
import numpy as np
x=[1,2,3,4,5,6]
y=[10,20,30,25,15,50]
# plt.plot(x,y)
# plt.plot(x,y,"m")
# plt.plot(x,y,"m",linewidth=4)
plt.plot(x,y,"m",linewidth=2,marker="D")
plt.title("Graph1")
plt.xlabel("Param 1")
plt.ylabel("Param 2")
plt.show

import matplotlib.pyplot as plt
import numpy as np
m=np.arange(1,10,2)
s=[250,150,60,35,75]
plt.xlabel("Parameter 1")
plt.ylabel("Parameter 2")
plt.title("Graph2")
plt.bar(m,s,color=['b','g','r','k','m'],width=2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
m=np.arange(1,10,2)
s=[250,150,60,35,75]
plt.xlabel("Parameter 1")
plt.ylabel("Parameter 2")
plt.title("Graph2")
plt.barh(m,s,color=['b','g','r','k','m'])
plt.show()

import matplotlib.pyplot as plt
import numpy as np
m=np.arange(1,10,2)
s=[250,150,60,35,75]
i=[10,50,60,30,45]
plt.xlabel("Parameter 1")
plt.ylabel("Parameter 2")
plt.title("Graph2")
plt.barh(m,s,color='r')
plt.barh(m+.25,i,color='b')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
salary=[15000,8000,7500,12000]
ename=['A','B','C','D']
c=['m','g','r','b']
e=[0,0,0,0.2]
plt.pie(salary,labels=ename,colors=c,explode=e,autopct="%.4f%%")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=sns.load_dataset("titanic") #others are Tips Iris Penguins Flights Diamonds Titanic Exercise MPG Planets
print(df.columns)
print(df.head())
print(df.info())
#df=sns.load_dataset("iris") my dataset
plt.plot(df['age'],linestyle='--',color='m')
plt.xlabel('Fare')
plt.ylabel('Age')
plt.legend("r")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=sns.load_dataset("titanic")
# survive_count=df['Survived'].value_counts.unstack()
# survive_count.plot(kind='bar',stacked=True)
# plt.show()