# -*- coding: utf-8 -*-
"""Model_Export.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QNra9M5703U_MzNl2NihHsvuBJSdloXA
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df=pd.read_csv("hpm.csv")
print(df.columns)
print(df.info())
print(df.describe())
print(df.ndim)
print(df.columns)
print(df.shape)
plt.scatter(df.area,df.price,color='m',marker='D')

from sklearn import linear_model
from sklearn.model_selection import train_test_split
import pickle

X=df['area']
y=df['price']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)
l_g=linear_model.LinearRegression()
l_g.fit(X_train.values.reshape(-1,1),y_train)
coff=l_g.coef_
incpt=l_g.intercept_
print(coff,incpt)
y_pred=l_g.predict([[3000]])
print(y_pred)
print(3200*coff+incpt)

pr_model='ROHIT.model'
fp=open(pr_model,'wb')
l_g=pickle.dump(l_g,fp)
fp.close()

