# -*- coding: utf-8 -*-
"""Model_Import.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFX--MvQWLEbJWByKsgwsr02YA0lv8n4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
import seaborn as sns
import pickle
fp=open('LR_Keshav.model','rb')
l_g=pickle.load(fp)
y_pr=l_g.predict([[3000]])
print(y_pr)